# Generated by Django 5.0.2 on 2024-02-08 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='spotimages',
            name='spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spot_images', related_query_name='spot_images', to='catalog.spot', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='spotmainimage',
            name='spot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spot_mainimage', related_query_name='spot_mainimage', to='catalog.spot', verbose_name='озеро'),
        ),
    ]
