# Generated by Django 4.2.5 on 2024-04-05 19:31

import catalog.validators
import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_spot_is_suburban'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=150, validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='название')),
                ('text', ckeditor.fields.RichTextField(help_text='Введите описание', validators=[catalog.validators.MaxWordsValidator(1000)], verbose_name='Текст')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания маршрута')),
                ('region', models.ForeignKey(blank=True, default=None, help_text='Выберите или добавьте регион', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_region', related_query_name='route_region', to='catalog.region', verbose_name='Регион')),
                ('spots', models.ManyToManyField(help_text='Выберите или добавьте место', to='catalog.spot', verbose_name='spots')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'маршрут',
                'verbose_name_plural': 'маршруты',
            },
        ),
    ]
