# Generated by Django 4.2.5 on 2024-04-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_spot_is_suburban'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='spots',
            field=models.ManyToManyField(help_text='Выберите или добавьте место', to='catalog.spot', verbose_name='места'),
        ),
    ]
