# Generated by Django 4.2.5 on 2024-04-27 18:10

from django.db import migrations, models
import django.db.models.deletion
import routes.models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_route_spots'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteMainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=routes.models.RouteMainImage.upload_to, verbose_name='изображение')),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route_mainimage', related_query_name='route_mainimage', to='routes.route', verbose_name='озеро')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
        migrations.CreateModel(
            name='RouteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=routes.models.RouteImages.upload_to, verbose_name='изображение')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_images', related_query_name='route_images', to='routes.route', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'изображения',
                'verbose_name_plural': 'изображения',
            },
        ),
    ]
